// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGpt0RrvuNiheaNalVnCd8zpwLM52FksY',
    appId: '1:221105577025:web:769e15d53a37888c807ac0',
    messagingSenderId: '221105577025',
    projectId: 'chat-app-9f04a',
    authDomain: 'chat-app-9f04a.firebaseapp.com',
    storageBucket: 'chat-app-9f04a.appspot.com',
    measurementId: 'G-GMV141NTNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7PpYjkMeZhpd_k5-B4iUzsWweJihI6GI',
    appId: '1:221105577025:android:1ade4bcd457d5049807ac0',
    messagingSenderId: '221105577025',
    projectId: 'chat-app-9f04a',
    storageBucket: 'chat-app-9f04a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvQcQZ4hBuu3_EjdMK8WYemjOSxK4bXg',
    appId: '1:221105577025:ios:789d002fbdd40299807ac0',
    messagingSenderId: '221105577025',
    projectId: 'chat-app-9f04a',
    storageBucket: 'chat-app-9f04a.appspot.com',
    iosClientId: '221105577025-f5j5o233ftshatlh4luk62b9bo0tk4k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvQcQZ4hBuu3_EjdMK8WYemjOSxK4bXg',
    appId: '1:221105577025:ios:789d002fbdd40299807ac0',
    messagingSenderId: '221105577025',
    projectId: 'chat-app-9f04a',
    storageBucket: 'chat-app-9f04a.appspot.com',
    iosClientId: '221105577025-f5j5o233ftshatlh4luk62b9bo0tk4k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
